name: Node.js CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Build Dragselect
        run: yarn build:dragselect

      - name: Test
        run: yarn test

      - name: List
        run: cd DragSelect && ls -la

      - name: Build Docs
        run: yarn build:docs

      - name: Build Files
        run: node ./build.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }} # only on master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # Set in the settings page of your repository, as a secure variable
          publish_dir: ./docs
          cname: DragSelect.com
